development:
  adapter: postgresql
  database: gif_guesser_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: gif_guesser_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: gif_guesser_production
  pool: 5
  timeout: 5000